#1
SELECT 
	BC.IDTB_BANCO AS 'ID BANCO',
    BC.NOMEBANCO AS 'NOME DO BANCO',
    AG.IDTB_AGENCIA AS 'ID AGENCIA',
	AG.NOMEAGENCIA AS 'NOME DA AGENCIA'
FROM TB_AGENCIA AS AG
INNER JOIN TB_BANCO AS BC
ON BC.IDTB_BANCO = AG.FKIDTB_BANCO;

#2
SELECT 
	BC.NOMEBANCO AS 'NOME DO BANCO',
    COUNT(AG.IDTB_AGENCIA) AS 'QUANTIDADE DE AGÊNCIA'
FROM TB_BANCO AS BC
INNER JOIN TB_AGENCIA AS AG
ON BC.IDTB_BANCO = AG.FKIDTB_BANCO
GROUP BY BC.NOMEBANCO
HAVING COUNT(AG.IDTB_AGENCIA) > 3;

#3
SELECT
	BC.NOMEBANCO AS 'NOME DO BANCO',
    AG.NOMEAGENCIA AS 'NOME DA AGÊNCIA',
    AG.IDTB_AGENCIA AS 'CÓDIGO DA AGÊNCIA'
FROM TB_AGENCIA AS AG
INNER JOIN TB_BANCO AS BC
ON AG.FKIDTB_BANCO = BC.IDTB_BANCO
WHERE (AG.NOMEAGENCIA = 'CENTRO' 
	OR AG.NOMEAGENCIA = 'JUSTIÇA DO TRABALHO')
    AND (BC.NOMEBANCO = 'BANCO DO BRASIL' OR NOMEBANCO = 'BRADESCO')
ORDER BY BC.NOMEBANCO ASC;

#4
SELECT
	BC.IDTB_BANCO AS 'CÓDIGO DO BANCO',
    BC.NOMEBANCO AS 'NOME DO BANCO',
    COUNT(AG.IDTB_AGENCIA) AS 'QUANTIDADE DE AGÊNCIA'
FROM TB_BANCO AS BC
INNER JOIN TB_AGENCIA AS AG
ON BC.IDTB_BANCO = AG.FKIDTB_BANCO
GROUP BY 1
ORDER BY 3 DESC, 1;

#5
SELECT
	CONCAT(NOMECLIENTE, SOBRENOMECLIENTE) AS NOME,
    NUMEROCONTA AS 'NÚMERO DA CONTA'
FROM TB_CLIENTE
INNER JOIN TB_CONTA
ON IDTB_CLIENTE = FKIDTB_CLIENTE
GROUP BY 1
HAVING COUNT(IDTB_CONTA) = 1;

#6
SELECT
	NOMEBANCO,
    NOMEAGENCIA,
    NUMEROCONTA,
    CONCAT(NOMECLIENTE, SOBRENOMECLIENTE) AS NOME
FROM TB_CLIENTE
INNER JOIN TB_CONTA ON IDTB_CLIENTE = FKIDTB_CLIENTE
INNER JOIN TB_AGENCIA ON IDTB_AGENCIA = FKIDTB_AGENCIA
INNER JOIN TB_BANCO ON IDTB_BANCO = FKIDTB_BANCO;

#7
SELECT
	NOMEAGENCIA 'AGÊNCIA',
    COUNT(IDTB_CONTA) 'QUANTIDADE DE CONTAS'
FROM TB_AGENCIA
INNER JOIN TB_CONTA ON IDTB_AGENCIA = FKIDTB_AGENCIA
GROUP BY 1
HAVING COUNT(IDTB_CONTA) > 2;

#8
SELECT
	NUMEROCONTA CONTA,
	CONCAT(NOMECLIENTE, ' ', SOBRENOMECLIENTE) AS CLIENTE,
    TIMESTAMPDIFF(YEAR, DTNASCIMENTO, CURDATE()) AS IDADE
FROM TB_CLIENTE
INNER JOIN TB_CONTA ON IDTB_CLIENTE = FKIDTB_CLIENTE
WHERE TIMESTAMPDIFF(YEAR, DTNASCIMENTO, CURDATE()) >= 35
ORDER BY 3 DESC;



